# Generated by Django 4.0.4 on 2025-12-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='chefproductimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
    ]
