# Generated by Django 3.2 on 2022-05-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Region',
            new_name='region',
        ),
    ]
