# Generated by Django 3.2 on 2022-05-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_region_product_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefs_preparing_product',
            old_name='Type_Food',
            new_name='type_food',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Type_Food',
            new_name='type_food',
        ),
    ]
