# Generated by Django 3.2 on 2022-05-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220526_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs_preparing_product',
            name='pdtid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chefs_preparing_product',
            name='product_image',
            field=models.ImageField(upload_to='Chefproductimg'),
        ),
        migrations.AlterField(
            model_name='chefs_preparing_product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
