# Generated by Django 3.2 on 2022-05-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_chefs_preparing_product_pdtid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefs_preparing_product',
            name='pdtid',
        ),
        migrations.AddField(
            model_name='chefs_preparing_product',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
    ]
