# Generated by Django 3.2 on 2022-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220526_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefs_preparing_product',
            name='type_food',
            field=models.CharField(choices=[('B', 'BreakFast'), ('L', 'Lunch'), ('D', 'Dinner'), ('R', 'Refreshers')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_food',
            field=models.CharField(choices=[('B', 'BreakFast'), ('L', 'Lunch'), ('D', 'Dinner'), ('R', 'Refreshers')], max_length=1),
        ),
    ]
