# Generated by Django 3.2 on 2022-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220526_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefs_preparing_product',
            name='category',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('NonVegetarian', 'NonVegetarian')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chefs_preparing_product',
            name='type_food',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Refreshers', 'Refreshers')], max_length=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('NonVegetarian', 'NonVegetarian')], max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_food',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Refreshers', 'Refreshers')], max_length=25),
        ),
    ]
