# Generated by Django 3.2 on 2022-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220526_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='prefers',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Indian', 'Indian'), ('others', 'others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Indian', 'Indian'), ('others', 'others')], max_length=50),
        ),
    ]
