# Generated by Django 3.2 on 2022-05-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220526_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefs_preparing_product',
            old_name='title',
            new_name='titleid',
        ),
    ]
