# Generated by Django 4.0.4 on 2022-05-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_customer_locality_remove_customer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.PositiveIntegerField(default=910000000000),
        ),
    ]
