# Generated by Django 4.0.4 on 2022-05-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='machineid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
