# Generated by Django 4.0.4 on 2022-05-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_orderplaced_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='user',
        ),
    ]
