# Generated by Django 4.0.4 on 2022-05-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
